### ISSUE TITLE
代码生成，成功之后提示 Dialog 源码？

### ISSUE THREAD

**Issue by wuchangfeng** [githubwing/MVPHelper#12]
你好，请问一下在代码生成成功之后(Readme 中第一张图)，那个提示 “success...” 的 Dialog 源码在哪，我找了一下 MessageCenter 中，测试发现效果不是**从上往下掉落**生成的样式。

very thx.

**Comment by githubwing** [comment]
那段代码我删了 。不过就是使用MessageCenter里的弹出的呀

**Comment by wuchangfeng** [comment]
https://github.com/githubwing/MVPHelper/blob/master/src/com/wingsofts/mvphelper/MessagesCenter.java#L14

是这一段吗？是不是有可能同样的代码，在 Win 下和 Mac 下表现形式不同？我只在我的 Win 台式机下测试了一下。我想在我写的插件中引入从上往下弹出的 Dialog。

**Comment by ZhouGongZaiShi** [comment]
@wuchangfeng 不除意外的话是这样的。Mac 下弹出的对话框是居中从上往下出现的。
