### ISSUE TITLE
AndroidStudio生成mvp有问题

### ISSUE THREAD

**Issue by yutf99** [githubwing/MVPHelper#13]
大兄弟，按照你的步骤，创建了presenter包，创建了一个presenter接口，在里面generate,然后就这样了
presenter
                          --SettingPresenter
SettingPresenter.javamodel
                          --SettingModel
                          --SettingModelImp
SettingPresenter.javapresenter
                         --SettingPresenterImp
SettingPresenter.javaview
                         --SettingView
这个包有点乱套了吧

**Comment by githubwing** [comment]
已解决，请更新
