### ISSUE TITLE
[Feature Request]请求支持自定义生成类所在的包路径

### ISSUE THREAD

**Issue by DevDengChao** [githubwing/MVPHelper#15]
测试了一下这个插件,发现两种生成方式默认的输出都是按照业务模块进行生成的.
分别要求当前类名包含Contract/Presenter, 然后在 ../ 目录下生成contract,model以及presenter包和对应的接口.
当我试图保留项目原有结构, 并利用该插件进行重构时,发现并不能找到能够设置参数的地方..

因此请求支持一下自定义生成类所在的包路径. 
或根据当前类所在的包, 一路向上解析到contract/presenter包的上一层(根目录), 然后追加当前类的包结构合适吗?

![qq 20170405174247](https://cloud.githubusercontent.com/assets/16363180/24699642/4d169cda-1a27-11e7-85f4-9483c1e13b89.png)
(既然已经在重构了,为何不连项目结构也一起改了呢..懒蛋)(连项目结构也一起重构ing)

**Comment by githubwing** [comment]
多谢你贡献代码
