### ISSUE TITLE
不清楚#1是不是和我的情况一样(package/import still fail)

### ISSUE THREAD

**Issue by hkq325800** [githubwing/MVPHelper#2]
package D:.code.mine.MyBase.userpart.src.main.java.{packageName}.{moduleName}.presenter;
import D:.code.mine.MyBase.userpart.src.main.java.{packageName}.{moduleName}.contract.HiContract;
会根据我的物理路径生成package 和 import,Version1.3.2 下载的链接是https://github.com/githubwing/MVPHelper/raw/master/MVPHelper.jar

**Comment by githubwing** [comment]
可否把相关截图发送至我邮箱？ androidwing1992@gmail.com

**Comment by githubwing** [comment]
你好，这是可能是由于包名判断出错引起的。目前判断以com org cn三种情况来判断，请修改包名重试下~

**Comment by hkq325800** [comment]
哦哦 好的
