### ISSUE TITLE
android studio 2.3.2插件不能使用

### ISSUE THREAD

**Issue by 127001david** [githubwing/MVPHelper#20]
我在最新版本android studio上使用MVPHelper的Contract模式时并没有生成所需的各个文件，而是直接将已经建好的Contract类文件删除了，请问这是什么原因？谢谢。
fu'dai附带错误日志截图：
![error_log](https://cloud.githubusercontent.com/assets/7624936/26812288/7c124964-4aa9-11e7-83ba-082156859f96.png)

**Comment by ckfree** [comment]
遇到相同的问题！

**Comment by githubwing** [comment]
目前此版本我已经不在维护， 请联系@XieEDeHeiShou 尝试解决☺

**Comment by DevDengChao** [comment]
Copy that.
晚上我回去测一下.
能够提供的具体操作步骤么?
@127001david @ckfree

**Comment by ckfree** [comment]
v2.3已经解决了这个问题，非常感谢！

**Comment by RockyQu** [comment]
as版本已经是2.3，3.0的也试了，也是报这个错，为啥啊？
