### ISSUE TITLE
我定义俩个相同名字的契约类，但是不在一个包内，我的同名的Model,Presenter文件会变删掉！！！恶心死我了，幸亏我记得逻辑

### ISSUE THREAD

**Issue by Cuiernao** [githubwing/MVPHelper#29]
*If you are creating a new issue, make sure you could provide a piece of `bug report` / `stacktrace` / `screenshot`.*
*It's a little bit hard to fix a bug according to a single sentence*

**Comment by DevDengChao** [comment]
已重现该问题. 
正在调试.

现阶段能提供的解决方案:
+ 按 <kbd>Ctrl + Z</kbd> 撤销非预期结果的操作;
+ 使用不同的名称对类进行命名.

**Comment by Cuiernao** [comment]
Ctrl+z不行，撤销不了我试过了！

**Comment by DevDengChao** [comment]
刚刚更新了, 试试 2.4 版吧.

**Comment by Cuiernao** [comment]
OK 非常感谢！
