### ISSUE TITLE
包名路径报错

### ISSUE THREAD

**Issue by zabio** [githubwing/MVPHelper#3]
macos , AS 2.2.1
以.Users.xxx.xxx.xxx.MvpDemo.app.src.main.java.model
导入会报错
'class' or 'interface' expected

**Comment by githubwing** [comment]
请问您的包名是不是不是以cn/org/com开头的，源码内是以这三个开头来判断是不是包名的。。这里有待改善，你先改下包名试试

**Comment by zabio** [comment]
刚刚测试以非com/org/cn 开头也有这个问题

**Comment by githubwing** [comment]
请问可以提供我相关截图吗，谢谢！androidwing1992@gmail.com

**Comment by zabio** [comment]
<img width="2410" alt="test" src="https://cloud.githubusercontent.com/assets/6436218/19473605/f1d6cacc-955e-11e6-8ff1-9943ef48f929.png">

**Comment by githubwing** [comment]
麻烦提供下com时候的情况。。现在是com/org/cn是正常的

**Comment by zabio** [comment]
![wechatimg2](https://cloud.githubusercontent.com/assets/6436218/19473778/8a195688-955f-11e6-8f41-f20f2765123c.jpg)

**Comment by zabio** [comment]
仔细看了下 contract包必须是建立在项目路径内是可以的 但是非com还是有问题

**Comment by githubwing** [comment]
非com会有问题，我需要统计一下常用的前缀，然后非contract应该会有dialog的吧
