### ISSUE TITLE
按照功能分包时无法生成

### ISSUE THREAD

**Issue by ayuhani** [githubwing/MVPHelper#4]
您好，我是按照功能分包的，比如说com.xx.example.login，我在这个包建类LoginContract，然后打算在相同包下生成presenter view 和model，请问这样有办法实现吗

**Comment by githubwing** [comment]
有办法实现是有办法，但是这种情况就无法与前面两种情况兼容，如果每次都弹dialog，用户体验会很差。。所以没有提供该功能    您可以尝试参考代码 自己实现

**Comment by ayuhani** [comment]
那我就在每个功能的模块下多分三个包吧
您以后会打算单独出一个插件来实现这个功能吗....

**Comment by githubwing** [comment]
以后可能会考虑整合到一起

**Comment by ayuhani** [comment]
多谢了
