### ISSUE TITLE
做好事要留名？MVPHelper是雷锋的学生吗

### ISSUE THREAD

**Issue by FanYimin** [githubwing/MVPHelper#5]
/**
- Created by MVPHelper on 2016/10/22
  */

注释上的名字改成MVPHelper了，如何让它恢复成我自己的名字？

**Comment by githubwing** [comment]
抱歉带给你这样的困扰，稍后会去掉。

**Comment by FanYimin** [comment]
回复这么快，赞一个。开个玩笑了，不用抱歉

**Comment by githubwing** [comment]
已更新
