### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by yuanshenbin** [githubwing/MVPHelper#7]
生成mvp后 出现Created by Ԭ���� on 2016/10/28乱码，
我自己修改了下。
old :         BufferedWriter writer = new BufferedWriter(new FileWriter(file));  
new :       Writer w = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file), "UTF-8"));
   BufferedWriter writer = new BufferedWriter(w);

**Comment by githubwing** [comment]
多谢，已修复
